import { defineConfig } from "tsup";

const openAiComponentExternals = [
  "Alert",
  "AppsSDKUIProvider",
  "Avatar",
  "Badge",
  "Button",
  "Checkbox",
  "CodeBlock",
  "DatePicker",
  "DateRangePicker",
  "EmptyMessage",
  "Icon",
  "Image",
  "Indicator",
  "Input",
  "Markdown",
  "Menu",
  "Popover",
  "RadioGroup",
  "SegmentedControl",
  "Select",
  "SelectControl",
  "ShimmerText",
  "Slider",
  "Switch",
  "TagInput",
  "Textarea",
  "TextLink",
  "Tooltip",
  "Transition",
].map((name) => `@openai/apps-sdk-ui/components/${name}`);

export default defineConfig({
  entry: {
    "core/index": "packages/core/src/index.ts",
    "client/index": "packages/client/src/index.ts",
    "auth/index": "packages/auth/src/index.ts",
    "anthropic/index": "packages/anthropic/src/index.ts",
    "anthropic/agent": "packages/anthropic/src/agent.ts",
    "anthropic/command": "packages/anthropic/src/command.ts",
    "anthropic/components": "packages/anthropic/src/components.tsx",
    "anthropic/hooks": "packages/anthropic/src/hooks.ts",
    "anthropic/mcp": "packages/anthropic/src/mcp.ts",
    "anthropic/plugin": "packages/anthropic/src/plugin.ts",
    "anthropic/skill": "packages/anthropic/src/skill.ts",
    "compiler/index": "packages/compiler/src/index.ts",
    "server/index": "packages/server/src/index.ts",
    "server/proxy": "packages/server/src/proxy.ts",
    "cli/index": "packages/cli/src/index.ts",
    "create-sidecar-app/index": "packages/create-sidecar-app/src/index.ts",
    "sidecar-ai/index": "packages/sidecar-ai/src/index.ts",
    "sidecar-ai/sidecar": "packages/sidecar-ai/src/sidecar.ts",
    "openai/index": "packages/openai/src/index.ts",
    "openai/components": "packages/openai/src/components.tsx",
    "openai/official": "packages/openai/src/official.ts",
    "react/index": "packages/react/src/index.ts",
    "native/index": "packages/native/src/index.ts",
    "native/components/index": "packages/native/src/components/index.tsx"
  },
  clean: true,
  dts: true,
  external: [
    "tsx",
    "ts-morph",
    "typescript",
    "@ts-morph/common",
    "esbuild",
    "react",
    "react-dom",
    "zod",
    "postcss",
    "autoprefixer",
    "@tailwindcss/postcss",
    "tailwindcss",
    "@tailwindcss/oxide",
    "@sidecar-ai/native",
    "@sidecar-ai/native/components",
    "@sidecar-ai/client",
    "@sidecar-ai/cli",
    "@modelcontextprotocol/sdk",
    "@modelcontextprotocol/sdk/types.js",
    "@modelcontextprotocol/ext-apps",
    "@modelcontextprotocol/ext-apps/app-with-deps",
    "@openai/apps-sdk-ui/css",
    ...openAiComponentExternals
  ],
  format: ["esm"],
  minify: false,
  outDir: "dist",
  sourcemap: true,
  splitting: false,
  target: "node20"
});
