/** Build orchestration for Sidecar projects. */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { analyzeProjectTools } from "./analyze.js";
import { writeGeneratedTypes } from "./generated.js";
import { buildPluginPackages } from "./plugins.js";
import type { BuildProjectOptions, SidecarManifest } from "./types.js";
import { buildWidgets } from "./widgets.js";

/** Builds the MCP output, generated types, and optional plugin packages. */
export async function buildProject(
  options: BuildProjectOptions,
): Promise<SidecarManifest> {
  const rootDir = path.resolve(options.rootDir);
  const tools = await analyzeProjectTools(rootDir);
  const outDir = path.resolve(rootDir, options.outDir ?? "out/mcp");
  await buildWidgets(rootDir, outDir, tools);

  const manifest: SidecarManifest = {
    version: 1,
    rootDir,
    generatedAt: new Date().toISOString(),
    tools,
  };

  await mkdir(outDir, { recursive: true });
  await writeFile(
    path.join(outDir, "manifest.sidecar.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFile(path.join(outDir, "README.md"), renderMcpReadme(manifest));
  await writeGeneratedTypes(rootDir, tools);
  if (options.plugins) {
    await buildPluginPackages(rootDir, path.dirname(outDir), manifest);
  }

  return manifest;
}

/** Renders a short build README with detected tools and install context. */
function renderMcpReadme(manifest: SidecarManifest): string {
  const tools = manifest.tools
    .map((toolEntry) => `- \`${toolEntry.id}\`: ${toolEntry.description}`)
    .join("\n");

  return `# Sidecar MCP Build

Generated by Sidecar.

## Tools

${tools || "No tools detected."}
`;
}
