/** Build orchestration for Sidecar projects. */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { analyzeProjectTools } from "./analyze.js";
import { analyzeProjectConfig } from "./config.js";
import { collectProjectDiagnostics, formatDiagnostic } from "./diagnostics.js";
import { writeGeneratedTypes } from "./generated.js";
import { buildPluginPackages } from "./plugins.js";
import { analyzeProjectPrompts } from "./prompts.js";
import { analyzeProjectResources } from "./resources.js";
import type { BuildProjectOptions, SidecarManifest, SidecarResourceTemplateManifestEntry } from "./types.js";
import { buildWidgets } from "./widgets.js";

/** Builds the MCP output, generated types, and optional plugin packages. */
export async function buildProject(
  options: BuildProjectOptions,
): Promise<SidecarManifest> {
  const rootDir = path.resolve(options.rootDir);
  const target = options.target ?? "mcp";
  const config = analyzeProjectConfig(rootDir);
  const tools = await analyzeProjectTools(rootDir, { target });
  const resources = await analyzeProjectResources(rootDir);
  const resourceTemplates: SidecarResourceTemplateManifestEntry[] = [];
  const prompts = await analyzeProjectPrompts(rootDir);
  const diagnostics = await collectProjectDiagnostics(rootDir, {
    tools,
    resources,
    prompts,
    config,
  });
  const errors = diagnostics.filter((diagnostic) => diagnostic.severity === "error");
  if (errors.length) {
    throw new Error(errors.map(formatDiagnostic).join("\n"));
  }

  const outDir = resolveInsideRoot(rootDir, options.outDir ?? "out/mcp");
  await buildWidgets(rootDir, outDir, tools);

  const manifest: SidecarManifest = {
    version: 1,
    target,
    rootDir: ".",
    generatedAt: new Date().toISOString(),
    config,
    tools,
    resources,
    resourceTemplates,
    prompts,
    diagnostics,
  };

  await mkdir(outDir, { recursive: true });
  await writeFile(
    path.join(outDir, "manifest.sidecar.json"),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFile(path.join(outDir, "README.md"), renderMcpReadme(manifest));
  await writeGeneratedTypes(rootDir, tools);
  if (options.plugins) {
    await buildPluginPackages(rootDir, path.dirname(outDir), manifest);
  }

  return manifest;
}

/** Resolves build output paths while preventing writes outside the project. */
function resolveInsideRoot(rootDir: string, output: string): string {
  const resolved = path.resolve(rootDir, output);
  const relative = path.relative(rootDir, resolved);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Build output must stay inside the project root: ${output}`);
  }
  return resolved;
}

/** Renders a short build README with detected tools and install context. */
function renderMcpReadme(manifest: SidecarManifest): string {
  const tools = manifest.tools
    .map((toolEntry) => `- \`${toolEntry.id}\`: ${toolEntry.description}`)
    .join("\n");
  const resources = manifest.resources
    .map((resourceEntry) => `- \`${resourceEntry.uri}\`: ${resourceEntry.description ?? resourceEntry.name}`)
    .join("\n");
  const prompts = manifest.prompts
    .map((promptEntry) => `- \`${promptEntry.name}\`: ${promptEntry.description ?? promptEntry.title}`)
    .join("\n");

  return `# Sidecar MCP Build

Generated by Sidecar.

## Tools

${tools || "No tools detected."}

## Resources

${resources || "No resources detected."}

## Prompts

${prompts || "No prompts detected."}

## Local HTTPS Testing

Run \`sidecar dev --tunnel\` from the project root to start the local MCP server on Streamable HTTP and print a validated HTTPS MCP URL that can be added to ChatGPT, Claude, or a Claude plugin install. Temporary quick tunnels are public and best-effort; use a configured tunnel/domain or deployed preview for repeatable testing.
`;
}
