/** Generated widget client writer. */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { SidecarToolManifestEntry } from "./types.js";
import { toIdentifier, toImportSpecifier } from "./utils.js";

/** Writes `.sidecar/generated/tools.ts` for typed widget-initiated calls. */
export async function writeGeneratedTypes(
  rootDir: string,
  tools: SidecarToolManifestEntry[],
): Promise<void> {
  const generatedDir = path.join(rootDir, ".sidecar", "generated");
  await mkdir(generatedDir, { recursive: true });
  const appCallableTools = tools.filter(isAppCallable);
  const methodNames = uniqueMethodNames(appCallableTools.map((entry) => toIdentifier(entry.id)));

  const imports = appCallableTools
    .map(
      (entry, index) =>
        `import type tool${index} from ${JSON.stringify(toImportSpecifier(generatedDir, path.join(rootDir, entry.sourceFile), { extension: "js" }))};`,
    )
    .join("\n");
  const ids = appCallableTools
    .map((entry, index) => `  ${methodNames[index]}: ${JSON.stringify(entry.id)}`)
    .join(",\n");
  const toolTypes = appCallableTools
    .map(
      (entry, index) =>
        `  ${methodNames[index]}(params: ToolParams<typeof tool${index}>): Promise<ToolOutput<typeof tool${index}>>;`,
    )
    .join("\n");

  await writeFile(
    path.join(generatedDir, "tools.ts"),
    `/**
 * Generated Sidecar widget tool client.
 *
 * Do not edit this file directly; it is regenerated by sidecar build and
 * sidecar dev.
 */
${imports}
import { createToolClient } from "@sidecar/client";
import type { ToolResult } from "@sidecar/core";

type ExecuteOf<T> = T extends { execute: infer Execute } ? Execute : never;
type ToolParams<T> = ExecuteOf<T> extends (params: infer Params, ...args: any[]) => unknown ? Params : never;
type RawToolOutput<T> = Awaited<ReturnType<Extract<ExecuteOf<T>, (...args: any[]) => unknown>>>;
type ToolOutput<T> = RawToolOutput<T> extends ToolResult<infer Structured, any> ? Structured : never;

/** Machine names keyed by widget-friendly method names. */
export const toolIds = {
${ids}
} as const;

/** Typed callable tools available to widgets. */
export type WidgetTools = {
${toolTypes}
};

/** Default widget tool client backed by the host bridge. */
export const tools = createToolClient<WidgetTools>(toolIds);
`,
  );
}

/** Returns true when MCP Apps metadata allows widgets to call the tool. */
function isAppCallable(entry: SidecarToolManifestEntry): boolean {
  const ui = entry.descriptor._meta?.ui;
  if (!ui || typeof ui !== "object" || Array.isArray(ui)) {
    return true;
  }

  const visibility = (ui as { visibility?: unknown }).visibility;
  return !Array.isArray(visibility) || visibility.includes("app");
}

/** Ensures generated widget method names cannot silently collide. */
function uniqueMethodNames(names: string[]): string[] {
  const seen = new Map<string, number>();
  return names.map((name) => {
    const count = seen.get(name) ?? 0;
    seen.set(name, count + 1);
    return count === 0 ? name : `${name}${count + 1}`;
  });
}
