import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadProjectIdentity } from "./identity.js";
import { emitClaudeAgents } from "./plugin-components/agents.js";
import { copyCommands } from "./plugin-components/commands.js";
import { copyHooks } from "./plugin-components/hooks.js";
import { copyClaudePassthroughDirectories } from "./plugin-components/passthrough.js";
import { copySkills } from "./plugin-components/skills.js";
import type { ProjectIdentity, SidecarManifest } from "./types.js";
import { existsSyncSafe, stripUndefined } from "./utils.js";

export async function buildPluginPackages(
  rootDir: string,
  outRoot: string,
  manifest: SidecarManifest,
): Promise<void> {
  const identity = await loadProjectIdentity(rootDir);
  await Promise.all([
    buildCodexPlugin(rootDir, outRoot, identity, manifest),
    buildClaudePlugin(rootDir, outRoot, identity, manifest),
  ]);
}

async function buildCodexPlugin(
  rootDir: string,
  outRoot: string,
  identity: ProjectIdentity,
  manifest: SidecarManifest,
): Promise<void> {
  const pluginDir = path.join(outRoot, "codex-plugin");
  await mkdir(path.join(pluginDir, ".codex-plugin"), { recursive: true });
  await copySkills(rootDir, path.join(pluginDir, "skills"));
  await copyHooks(rootDir, path.join(pluginDir, "hooks"));

  await writeJson(path.join(pluginDir, ".codex-plugin", "plugin.json"), {
    name: identity.slug,
    version: identity.version,
    description: identity.description,
    displayName: identity.name,
    mcpServers: "./.mcp.json",
    apps: "./.app.json",
    skills: existsSyncSafe(path.join(rootDir, "skills"))
      ? "./skills"
      : undefined,
  });

  await writeJson(path.join(pluginDir, ".mcp.json"), {
    mcpServers: {
      [identity.slug]: {
        type: "http",
        url: "${SIDECAR_MCP_URL}",
      },
    },
  });

  await writeJson(path.join(pluginDir, ".app.json"), {
    apps: manifest.tools
      .filter((entry) => entry.widget)
      .map((entry) => ({
        tool: entry.id,
        resourceUri: entry.widget?.resourceUri,
      })),
  });

  await writeFile(
    path.join(pluginDir, "README.md"),
    `# ${identity.name} Codex Plugin

This package was generated by Sidecar.

Set \`SIDECAR_MCP_URL\` to the hosted MCP endpoint for this app.

Codex plugin hooks are not generated unless the Sidecar project defines hooks, and host plugin hooks may require an explicit feature flag in Codex.
`,
  );
}

async function buildClaudePlugin(
  rootDir: string,
  outRoot: string,
  identity: ProjectIdentity,
  manifest: SidecarManifest,
): Promise<void> {
  const pluginDir = path.join(outRoot, "claude-plugin");
  await mkdir(path.join(pluginDir, ".claude-plugin"), { recursive: true });
  await copySkills(rootDir, path.join(pluginDir, "skills"));
  await copyCommands(rootDir, path.join(pluginDir, "commands"));
  await copyHooks(rootDir, path.join(pluginDir, "hooks"));
  await emitClaudeAgents(rootDir, path.join(pluginDir, "agents"));
  await copyClaudePassthroughDirectories(rootDir, pluginDir);

  await writeJson(path.join(pluginDir, ".claude-plugin", "plugin.json"), {
    name: identity.slug,
    version: identity.version,
    description: identity.description,
    displayName: identity.name,
    installationPreference: "available",
  });

  await writeJson(path.join(pluginDir, "version.json"), {
    version: identity.version,
    generatedBy: "sidecar",
  });

  await writeJson(path.join(pluginDir, ".mcp.json"), {
    mcpServers: {
      [identity.slug]: {
        type: "http",
        url: "${SIDECAR_MCP_URL}",
      },
    },
  });

  await writeJson(path.join(pluginDir, "settings.json"), {
    sidecar: {
      tools: manifest.tools.map((entry) => entry.id),
    },
  });

  await writeFile(
    path.join(pluginDir, "README.md"),
    `# ${identity.name} Claude Plugin

This package was generated by Sidecar.

Set \`SIDECAR_MCP_URL\` to the hosted MCP endpoint for this app.

Claude/Cowork plugin-specific components such as skills, slash commands, agents, hooks, output styles, themes, monitors, assets, and bin scripts will be emitted here when the source project defines them.
`,
  );
}

async function writeJson(
  filePath: string,
  value: Record<string, unknown>,
): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(
    filePath,
    `${JSON.stringify(stripUndefined(value), null, 2)}\n`,
  );
}
