/** Installable plugin generation for Codex and Claude Code. */
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadProjectIdentity } from "./identity.js";
import { emitClaudeAgents } from "./plugin-components/agents.js";
import { copyCommands } from "./plugin-components/commands.js";
import { copyHooks } from "./plugin-components/hooks.js";
import {
  copyClaudePassthroughDirectories,
  copyCodexPassthroughDirectories,
} from "./plugin-components/passthrough.js";
import { copySkills } from "./plugin-components/skills.js";
import { buildPluginDownloads } from "./plugin-downloads.js";
import type { ProjectIdentity, SidecarManifest } from "./types.js";
import { existsSyncSafe, stripUndefined } from "./utils.js";

const MCP_URL_PLACEHOLDER = "${SIDECAR_MCP_URL}";

/** Emits plugin directories, local marketplaces, and downloadable ZIP archives. */
export async function buildPluginPackages(
  rootDir: string,
  outRoot: string,
  manifest: SidecarManifest,
  mcpUrl = MCP_URL_PLACEHOLDER,
): Promise<void> {
  const identity = await loadProjectIdentity(rootDir);
  const codexPluginDir = path.join(outRoot, "codex-plugin");
  const claudePluginDir = path.join(outRoot, "claude-plugin");
  const codexMarketplaceDir = path.join(outRoot, "codex-marketplace");
  const claudeMarketplaceDir = path.join(outRoot, "claude-marketplace");

  await Promise.all(
    [codexPluginDir, claudePluginDir, codexMarketplaceDir, claudeMarketplaceDir].map(
      (directory) => rm(directory, { recursive: true, force: true }),
    ),
  );
  await Promise.all([
    buildCodexPlugin(rootDir, codexPluginDir, identity, manifest, mcpUrl),
    buildClaudePlugin(rootDir, claudePluginDir, identity, manifest, mcpUrl),
  ]);
  await buildPluginDownloads({
    outDir: outRoot,
    codex: {
      directory: codexPluginDir,
      mcpServer: { type: "http", url: mcpUrl },
    },
    claude: {
      directory: claudePluginDir,
      mcpServer: { type: "http", url: mcpUrl },
    },
  });
}

async function buildCodexPlugin(
  rootDir: string,
  pluginDir: string,
  identity: ProjectIdentity,
  manifest: SidecarManifest,
  mcpUrl: string,
): Promise<void> {
  await mkdir(path.join(pluginDir, ".codex-plugin"), { recursive: true });
  await copySkills(rootDir, path.join(pluginDir, "skills"));
  await copyCodexPassthroughDirectories(rootDir, pluginDir);

  await writeJson(path.join(pluginDir, ".codex-plugin", "plugin.json"), {
    name: identity.slug,
    version: identity.version,
    description: identity.description,
    author: { name: identity.name },
    skills: existsSyncSafe(path.join(rootDir, "skills"))
      ? "./skills/"
      : undefined,
    mcpServers: "./.mcp.json",
    interface: {
      displayName: identity.name,
      shortDescription: identity.description,
      longDescription: identity.description,
      developerName: identity.name,
      category: "Developer Tools",
      capabilities: pluginCapabilities(manifest),
      defaultPrompt: [
        `Use ${identity.name} when its tools or project context are relevant.`,
      ],
    },
  });
  await writeJson(path.join(pluginDir, ".mcp.json"), {
    mcpServers: {
      [identity.slug]: { type: "http", url: mcpUrl },
    },
  });
  await writeFile(
    path.join(pluginDir, "README.md"),
    `# ${identity.name} for Codex

Generated by Sidecar. This plugin connects Codex to ${identity.name} through its hosted MCP server.

Install the enclosing marketplace, then add \`${identity.slug}@${identity.slug}\` from Codex's plugin directory.
`,
  );
}

async function buildClaudePlugin(
  rootDir: string,
  pluginDir: string,
  identity: ProjectIdentity,
  manifest: SidecarManifest,
  mcpUrl: string,
): Promise<void> {
  await mkdir(path.join(pluginDir, ".claude-plugin"), { recursive: true });
  await copySkills(rootDir, path.join(pluginDir, "skills"));
  await copyCommands(rootDir, path.join(pluginDir, "commands"));
  await copyHooks(rootDir, path.join(pluginDir, "hooks"));
  await emitClaudeAgents(rootDir, path.join(pluginDir, "agents"));
  await copyClaudePassthroughDirectories(rootDir, pluginDir);

  await writeJson(path.join(pluginDir, ".claude-plugin", "plugin.json"), {
    name: identity.slug,
    version: identity.version,
    description: identity.description,
    displayName: identity.name,
    installationPreference: "available",
  });
  await writeJson(path.join(pluginDir, "version.json"), {
    version: identity.version,
    generatedBy: "sidecar",
  });
  await writeJson(path.join(pluginDir, "settings.json"), {
    sidecar: {
      tools: manifest.tools.map((entry) => entry.id),
      resources: manifest.resources.map((entry) => entry.uri),
      prompts: manifest.prompts.map((entry) => entry.name),
    },
  });
  await writeJson(path.join(pluginDir, ".mcp.json"), {
    mcpServers: {
      [identity.slug]: { type: "http", url: mcpUrl },
    },
  });
  await writeFile(
    path.join(pluginDir, "README.md"),
    `# ${identity.name} for Claude Code

Generated by Sidecar. This plugin connects Claude Code to ${identity.name} through its hosted MCP server.

Add the enclosing marketplace with \`/plugin marketplace add\`, then install \`${identity.slug}@${identity.slug}\`.
`,
  );
}

function pluginCapabilities(manifest: SidecarManifest): string[] {
  return [
    manifest.tools.length ? "Tools" : undefined,
    manifest.resources.length ? "Resources" : undefined,
    manifest.prompts.length ? "Prompts" : undefined,
  ].filter((value): value is string => Boolean(value));
}

async function writeJson(
  filePath: string,
  value: Record<string, unknown>,
): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(
    filePath,
    `${JSON.stringify(stripUndefined(value), null, 2)}\n`,
  );
}
